---
title: "CFLNM"
output: html_document
---


<style type="text/css">

/* Navbar Styles */
.navbar {
  background-color:  #00BFB3 !important; /* Background color of the navbar */
  border-color:   #00BFB3 !important; /* Border color of the navbar */
  background-image: none !important; /* Removes any background image */
  height: 65px; /* Sets navbar height */
}

/* Navbar Link Styles */
.navbar-default .navbar-nav > li > a {
  color: #FFFFFF !important;  /* Text color for links */
  font-weight: bold !important; /* Bold text */
}

.navbar-default .navbar-nav > li > a:hover,
.navbar-default .navbar-nav > li > a:focus {
  color: #D8CEFF !important; /* Hover and focus text color */
  font-weight: bold; /* Keeps text bold on hover/focus */
}

/* Navbar Collapse Menu Styles */
.navbar-collapse {
  background-color: #00BFB3 !important; /* Background color for the collapsed navbar */
}

/* Dropdown Menu Link Styles */
.navbar-nav > li > a {
  color: #D8CEFF; /* Text color for dropdown links */
  font-weight: bold;
  padding: 10px 15px; /* Padding for dropdown links */
}

.navbar-nav > li > a:hover,
.navbar-nav > li > a:focus,
.navbar-nav > .active > a {
  background-color:  #00BFB3; /* Background color on hover/active */
  color:  #00BFB3; /* Text color on hover/active */
}

/* Active List Group Item Styles */
.list-group-item.active,
.list-group-item.active:focus,
.list-group-item.active:hover {
  z-index: 2;
  color: #00BFB3; /* Text color for active list item */
  background-color:  #E4D0EF; /* Background color for active list item */
  border-color: #E4D0EF; /* Border color for active list item */
}

/* Title, Subtitle, Author, and Date Styles */
h1.title {
  color:  #003057; /* Color for title */
}

h4.subtitle {
  color:  #003057; /* Color for subtitle */
}

h5.author {
  color:  #003057; /* Color for author */
}

h5.date {
  color: #00BFB3; /* Color for date */
}


/* Hyperlink Styles */
a {
  color: #582C35; /* Text color for hyperlinks */
  text-decoration: none; /* Removes underline from hyperlinks */
}

a:hover {
  color: #005a9c; /* Color when hovering over hyperlinks */
  text-decoration: underline; /* Underlines text when hovering over hyperlinks */
}

a:visited {
  color: #6C4F56; /* Color for visited hyperlinks */
}

a:active {
  color: #4A2C31; /* Color for active hyperlinks (while clicking) */
}


/* Cambia el color del cuerpo del texto */
body {
  color: #2E3A46 !important; /* Un gris oscuro para mejorar la lectura */
}

/* Cambia el color de los p치rrafos */
p {
  color: #354A5F !important; /* Azul-gris치ceo m치s claro */
}

/* Cambia el color del texto en listas */
ul li {
  color: #005a9c !important; /* Azul m치s fuerte */
}

</style>


<div class="row" style="padding-top: 30px;">
<div class="col-sm-6" style="color:#00BFB3;">


